apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: site
        image: fabricioveronez/web-page:green
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector: 
    app: mypod
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort